# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: xcodebuild -scheme ZUKH -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12'
      - name: Test
        run: xcodebuild -scheme ZUKH -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12' test
        
